# Generated by Django 5.2.6 on 2025-11-20 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('line_points', 'Line Points'), ('homography', 'Homography Matrix'), ('radial', 'Radial Distortion'), ('other', 'Other')], default='line_points', max_length=32)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('source_image_path', models.CharField(blank=True, max_length=255)),
                ('artifact_file', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_artifacts', to='core.camera')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
