# Generated by Django 5.2.8 on 2025-11-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calibrationartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedframe',
            name='rectified_image',
            field=models.ImageField(blank=True, null=True, upload_to='frames/rectified/'),
        ),
    ]
