# Generated by Django 5.2.8 on 2025-11-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_capturedframe_rectified_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='motion_capture_pid',
            field=models.IntegerField(blank=True, help_text='PID of the running capture process, if any', null=True),
        ),
    ]
