# Generated by Django 5.2.8 on 2025-11-21 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_camera_motion_capture_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('source_image', models.ImageField(upload_to='calibration/source/')),
                ('rectified_preview', models.ImageField(blank=True, null=True, upload_to='calibration/preview/')),
                ('fit_error', models.FloatField(blank=True, null=True)),
                ('crop_rect', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('artifact_dir', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_sessions', to='core.camera')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationLinePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_index', models.IntegerField()),
                ('point_index', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_points', to='core.calibrationsession')),
            ],
            options={
                'ordering': ['line_index', 'point_index'],
            },
        ),
    ]
